### ISSUE TITLE
No Annotations Proposal

### ISSUE THREAD

**Issue by Adafede** [metwork-project/metwork-frontend#55]
Hi guys,

Just wanted to give a try at your tool but was quite surprised to get...0 annotation proposals.

(For info i ran it on a set of 4000 ions with 1000 annotated, with max depth = 4, all your rules and cosine tolerances of 0.02Da, 4 peaks, 0.2 score) I ran it directly on your server, molecules are properly imported and so on

Is there any explanation?

P.S.: There are some indole alkaloids in the set, so even more surprising :P

**Comment by GGentajouve** [comment]
Hi, 
Could you give me the project ID please?
Best

Gregory

**Comment by Adafede** [comment]
Hi,
I think it must be 1029 (at least what the browser is showing me), hope it helps!

**Comment by GGentajouve** [comment]
Well, it looks like the run crashed due to the large number of annotations used (n=1000) and transformations. Restarting the run with only depth=1 you get more than 1 000 000 molecules after few minutes. At the current rate, it should take roughly 6 hours to end. I would suggest creating new projects with less annotation and/or transformations.

**Comment by Adafede** [comment]
Hi, run just finished... 429236 molecules, 0 annotations...
( Project 1035)
